package sca

import (
	"path/filepath"
	"reflect"
	"testing"
)

// yarnClassic is the Yarn 1 format. Note what it does not contain: any record
// of which packages the project itself asked for. express and jest look exactly
// like the packages they drag in.
const yarnClassic = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


accepts@~1.3.7:
  version "1.3.8"
  resolved "https://registry.yarnpkg.com/accepts/-/accepts-1.3.8.tgz#0bf0be1"
  integrity sha512-PYAthTa2m2VKxuvSD3DPC
  dependencies:
    mime-types "~2.1.34"

"@babel/core@^7.0.0", "@babel/core@^7.1.0":
  version "7.20.0"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.20.0.tgz#abc"

express@4.17.1:
  version "4.17.1"
  resolved "https://registry.yarnpkg.com/express/-/express-4.17.1.tgz#def"
  dependencies:
    accepts "~1.3.7"
    qs "6.7.0"

jest@^29.0.0:
  version "29.7.0"
  resolved "https://registry.yarnpkg.com/jest/-/jest-29.7.0.tgz#ghi"

mime-types@~2.1.34:
  version "2.1.35"
  resolved "https://registry.yarnpkg.com/mime-types/-/mime-types-2.1.35.tgz#jkl"

orphan@^1.0.0:
  version "1.2.3"
  resolved "https://registry.yarnpkg.com/orphan/-/orphan-1.2.3.tgz#mno"

qs@6.7.0:
  version "6.7.0"
  resolved "https://registry.yarnpkg.com/qs/-/qs-6.7.0.tgz#pqr"
`

// yarnBerry is the same tree as Yarn 2 and later writes it: YAML, descriptors
// carrying the npm protocol, and a workspace entry standing for the project
// itself. Yarn 2.4 writes dependency edges without the protocol while the
// descriptors have it, which is the mismatch resolution has to absorb.
const yarnBerry = `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 4
  cacheKey: 7

"accepts@npm:~1.3.7":
  version: 1.3.8
  resolution: "accepts@npm:1.3.8"
  dependencies:
    mime-types: ~2.1.34
  languageName: node
  linkType: hard

"app@workspace:.":
  version: 0.0.0-use.local
  resolution: "app@workspace:."
  dependencies:
    express: 4.17.1
  languageName: unknown
  linkType: soft

"express@npm:4.17.1":
  version: 4.17.1
  resolution: "express@npm:4.17.1"
  dependencies:
    accepts: ~1.3.7
    qs: "npm:6.7.0"
  languageName: node
  linkType: hard

"mime-types@npm:~2.1.34":
  version: 2.1.35
  resolution: "mime-types@npm:2.1.35"
  languageName: node
  linkType: hard

"qs@npm:6.7.0":
  version: 6.7.0
  resolution: "qs@npm:6.7.0"
  languageName: node
  linkType: hard
`

func TestYarnClassic(t *testing.T) {
	dir := writeFiles(t, map[string]string{
		"yarn.lock":    yarnClassic,
		"package.json": `{"dependencies":{"express":"4.17.1"},"devDependencies":{"jest":"^29.0.0"}}`,
	})

	deps, err := (&YarnLockParser{}).Parse(filepath.Join(dir, "yarn.lock"))
	if err != nil {
		t.Fatalf("Parse returned error: %v", err)
	}

	t.Run("every entry is reported", func(t *testing.T) {
		want := []string{"@babel/core", "accepts", "express", "jest", "mime-types", "orphan", "qs"}
		if got := depNames(deps); !reflect.DeepEqual(got, want) {
			t.Errorf("parsed %v, want %v", got, want)
		}
	})

	t.Run("package.json decides what is direct", func(t *testing.T) {
		// yarn.lock cannot answer this on its own: an entry for a declared
		// dependency is indistinguishable from one six levels down.
		for _, name := range []string{"express", "jest"} {
			if d, _ := findDep(deps, name); !d.Direct {
				t.Errorf("%s is declared in package.json and should be direct", name)
			}
		}
		for _, name := range []string{"accepts", "qs", "mime-types"} {
			if d, _ := findDep(deps, name); d.Direct {
				t.Errorf("%s is required by another package, not declared", name)
			}
		}
	})

	t.Run("routes follow the requirement chain", func(t *testing.T) {
		tests := []struct {
			name string
			want []string
		}{
			{"express", nil},
			{"accepts", []string{"express"}},
			{"qs", []string{"express"}},
			{"mime-types", []string{"express", "accepts"}},
		}
		for _, tt := range tests {
			d, ok := findDep(deps, tt.name)
			if !ok {
				t.Fatalf("%s missing", tt.name)
			}
			if !reflect.DeepEqual(d.Path, tt.want) {
				t.Errorf("%s route = %v, want %v", tt.name, d.Path, tt.want)
			}
		}
	})

	t.Run("a header listing several requirements is one package", func(t *testing.T) {
		// "@babel/core@^7.0.0", "@babel/core@^7.1.0" resolve to one install.
		// Reporting it twice would mean two findings for one vulnerability.
		count := 0
		for _, d := range deps {
			if d.Name == "@babel/core" {
				count++
				if d.Version != "7.20.0" {
					t.Errorf("@babel/core version = %q, want 7.20.0", d.Version)
				}
			}
		}
		if count != 1 {
			t.Errorf("@babel/core reported %d times, want once", count)
		}
	})

	t.Run("unreached entries are still reported", func(t *testing.T) {
		d, ok := findDep(deps, "orphan")
		if !ok {
			t.Fatal("orphan was dropped; a package in the lockfile is installed code")
		}
		if d.Direct || len(d.Path) != 0 {
			t.Errorf("orphan should carry no route, got direct=%v path=%v", d.Direct, d.Path)
		}
	})
}

func TestYarnBerry(t *testing.T) {
	dir := writeFiles(t, map[string]string{
		"yarn.lock":    yarnBerry,
		"package.json": `{"dependencies":{"express":"4.17.1"}}`,
	})

	deps, err := (&YarnLockParser{}).Parse(filepath.Join(dir, "yarn.lock"))
	if err != nil {
		t.Fatalf("Parse returned error: %v", err)
	}

	t.Run("the workspace entry is not a package", func(t *testing.T) {
		// "app@workspace:." is this repository, at a placeholder version. It
		// has nothing to match an advisory against.
		if _, ok := findDep(deps, "app"); ok {
			t.Error("the workspace entry was reported as a dependency")
		}
		want := []string{"accepts", "express", "mime-types", "qs"}
		if got := depNames(deps); !reflect.DeepEqual(got, want) {
			t.Errorf("parsed %v, want %v", got, want)
		}
	})

	t.Run("edges resolve whether or not they carry the npm protocol", func(t *testing.T) {
		// express requires accepts as "~1.3.7" and qs as "npm:6.7.0", while
		// both descriptors are written with the protocol. Yarn versions differ
		// on which spelling they emit, so both have to resolve.
		for _, tt := range []struct {
			name string
			want []string
		}{
			{"accepts", []string{"express"}},
			{"qs", []string{"express"}},
			{"mime-types", []string{"express", "accepts"}},
		} {
			d, ok := findDep(deps, tt.name)
			if !ok {
				t.Fatalf("%s missing", tt.name)
			}
			if !reflect.DeepEqual(d.Path, tt.want) {
				t.Errorf("%s route = %v, want %v", tt.name, d.Path, tt.want)
			}
		}
	})

	t.Run("versions are the resolved ones", func(t *testing.T) {
		if d, _ := findDep(deps, "mime-types"); d.Version != "2.1.35" {
			t.Errorf("mime-types version = %q, want the resolved 2.1.35", d.Version)
		}
	})
}

// TestYarnWithoutPackageJSON pins the fallback: the lockfile alone still names
// every installed package, and only the direct/transitive split is lost.
func TestYarnWithoutPackageJSON(t *testing.T) {
	dir := writeFiles(t, map[string]string{"yarn.lock": yarnClassic})

	deps, err := (&YarnLockParser{}).Parse(filepath.Join(dir, "yarn.lock"))
	if err != nil {
		t.Fatalf("Parse returned error: %v", err)
	}

	if len(deps) != 7 {
		t.Errorf("parsed %d packages, want all 7 — a vendored lockfile is still a dependency list", len(deps))
	}
	for _, d := range deps {
		if d.Direct {
			t.Errorf("%s cannot be known to be direct with no package.json", d.Name)
		}
	}
}

// TestYarnIsDeterministic guards the same property the npm parser needs: a
// route that changes between runs of an unchanged scan makes every diff
// between two reports untrustworthy.
func TestYarnIsDeterministic(t *testing.T) {
	for _, tt := range []struct {
		name    string
		content string
	}{
		{"classic", yarnClassic},
		{"berry", yarnBerry},
	} {
		t.Run(tt.name, func(t *testing.T) {
			dir := writeFiles(t, map[string]string{
				"yarn.lock":    tt.content,
				"package.json": `{"dependencies":{"express":"4.17.1"}}`,
			})
			path := filepath.Join(dir, "yarn.lock")

			first, err := (&YarnLockParser{}).Parse(path)
			if err != nil {
				t.Fatalf("Parse returned error: %v", err)
			}
			for i := 0; i < 8; i++ {
				again, err := (&YarnLockParser{}).Parse(path)
				if err != nil {
					t.Fatalf("Parse returned error: %v", err)
				}
				if !reflect.DeepEqual(first, again) {
					t.Fatalf("run %d differs from the first", i+1)
				}
			}
		})
	}
}

// TestOneLockfilePerEcosystem covers a project carrying both npm and yarn
// lockfiles, which happens after a migration when the old file is not deleted.
// They describe one installation, so taking both would report every package
// twice.
func TestOneLockfilePerEcosystem(t *testing.T) {
	dir := writeFiles(t, map[string]string{
		"package-lock.json": lockV3,
		"yarn.lock":         yarnClassic,
		"package.json":      `{"dependencies":{"express":"4.17.1"}}`,
	})

	deps, err := New(dir).collectDependencies()
	if err != nil {
		t.Fatalf("collectDependencies returned error: %v", err)
	}

	counts := make(map[string]int)
	for _, d := range deps {
		counts[d.Name]++
	}
	for name, n := range counts {
		if n > 1 {
			t.Errorf("%s reported %d times; one ecosystem in one directory is described by one lockfile", name, n)
		}
	}

	// package-lock.json is registered first and wins, so the tree reported is
	// the one it describes.
	if _, ok := findDep(deps, "side-channel"); !ok {
		t.Error("expected the package-lock.json tree, which contains side-channel")
	}
	// mime-types appears only in the yarn fixture, so finding it would mean
	// both trees were taken.
	if _, ok := findDep(deps, "mime-types"); ok {
		t.Error("the yarn.lock tree was merged in as well")
	}
}
